import { createClient } from "@supabase/supabase-js";
import { createAdminClient } from "@/lib/supabase/admin";
import { logAudit } from "@/lib/supabase/audit";

// The tablet POSTs {appUserId, pin} after a staff member taps their name and
// enters their PIN. We verify the PIN (with DB lockout), then mint that
// operator's real Supabase session WITHOUT their password — a one-time
// magic-link token generated by the service role and immediately redeemed. The
// tablet imports the returned tokens, so every sale/job it creates is attributed
// to the real operator. Neither the service-role key nor any password ever
// reaches the tablet; the shared device key gates the endpoint.
export const dynamic = "force-dynamic";

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json" } });
}

function deviceOk(req: Request): boolean {
  const expected = process.env.POS_DEVICE_KEY;
  return !!expected && req.headers.get("x-pos-device-key") === expected;
}

export async function POST(req: Request) {
  if (!deviceOk(req)) return json({ error: "unauthorized" }, 401);

  let body: { appUserId?: unknown; pin?: unknown };
  try {
    body = await req.json();
  } catch {
    return json({ error: "bad_request" }, 400);
  }
  const appUserId = String(body?.appUserId ?? "");
  const pin = String(body?.pin ?? "");
  if (!/^[0-9a-f-]{36}$/i.test(appUserId) || !/^[0-9]{4}$/.test(pin)) return json({ error: "bad_request" }, 400);

  const admin = createAdminClient();

  // 1) verify the PIN (server-side, with per-user lockout)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: v, error: vErr } = await (admin as any).rpc("verify_staff_pin", { p_app_user_id: appUserId, p_pin: pin });
  if (vErr) return json({ error: "server_error" }, 500);
  if (!v?.ok) return json({ error: v?.reason ?? "invalid", lockedUntil: v?.locked_until ?? null }, 401);

  // 2) look up the operator's email (needed to mint a session)
  const { data: userRes, error: uErr } = await admin.auth.admin.getUserById(v.auth_user_id as string);
  const email = userRes?.user?.email;
  if (uErr || !email) return json({ error: "server_error" }, 500);

  // 3) mint a session without the password: generate a one-time magic-link token…
  const { data: linkData, error: lErr } = await admin.auth.admin.generateLink({ type: "magiclink", email });
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const tokenHash = (linkData as any)?.properties?.hashed_token as string | undefined;
  if (lErr || !tokenHash) return json({ error: "server_error" }, 500);

  // …and immediately redeem it with an anon client to get the session tokens.
  const anon = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
  const { data: otp, error: oErr } = await anon.auth.verifyOtp({ type: "magiclink", token_hash: tokenHash });
  const session = otp?.session;
  if (oErr || !session) return json({ error: "server_error" }, 500);

  // Record the POS sign-in for the Activity log (best-effort).
  try {
    const { data: au } = await admin.from("app_users").select("tenant_id").eq("id", appUserId).maybeSingle();
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const tenantId = (au as any)?.tenant_id;
    if (tenantId) await logAudit(admin, { tenantId, actorId: appUserId, eventType: "signed_in", refType: "app_user", refId: appUserId, payload: { device: "pos" } });
  } catch { /* ignore */ }

  return json({
    accessToken: session.access_token,
    refreshToken: session.refresh_token,
    expiresAt: session.expires_at,
    operator: { appUserId, displayName: v.display_name, role: v.role },
  });
}
