"use server";

import { headers } from "next/headers";
import { createAdminClient } from "@/lib/supabase/admin";
import { sendPasswordResetEmail } from "@/lib/email";

// "I forgot my password."
//
// This form TELLS YOU when an address has no account, at the owner's request,
// and that is a deliberate trade rather than an oversight — so it is worth
// writing down what was traded.
//
// The generic "if that address has an account, a link is on its way" hides the
// staff list from a stranger probing addresses. It also makes a typo look
// exactly like success: you wait for an email that was never coming. Here the
// logins are carfectionist+<firstname>@gmail.com — a pattern anyone can guess
// from the studio's public address — so the secret being kept was thin, while
// the confusion was real and landed on eight people who just want back in.
//
// What that costs: this endpoint is now an oracle. Anyone can ask it whether an
// address has an account. Two things carry the weight that the vague message
// used to:
//   • the throttle, per address AND per IP, counted BEFORE the lookup so that
//     probing burns the quota whether or not the address exists;
//   • nothing else on the page reveals more than existence — not the name, not
//     the role, not whether a link was ever sent before.
//
// Everything else got more honest as a result: a mailer failure now says so
// instead of claiming success, and a deactivated account says so instead of
// silently going nowhere.
//
// The link itself is a Supabase recovery token generated by the service role and
// delivered by OUR mailer — see sendPasswordResetEmail for why not Supabase's.

export interface ForgotState {
  sent?: boolean;
  sentTo?: string;
  error?: string;
}

const PER_EMAIL = { max: 3, minutes: 15 };
const PER_IP = { max: 10, minutes: 60 };
const LINK_MINUTES = 60; // Supabase's default recovery TTL

export async function requestPasswordReset(_prev: ForgotState, formData: FormData): Promise<ForgotState> {
  const raw = String(formData.get("email") ?? "").trim();
  const emailKey = raw.toLowerCase();
  if (!raw || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(raw)) return { error: "Enter a valid email address." };

  const h = await headers();
  const ip = h.get("cf-connecting-ip") ?? h.get("x-forwarded-for")?.split(",")[0]?.trim() ?? null;
  const origin = originFrom(h);

  // The service role is the only thing that touches the throttle table (RLS on,
  // no policies, grants revoked) and the only thing that can mint a token.
  const admin = createAdminClient();

  try {
    const now = Date.now();
    const since = (mins: number) => new Date(now - mins * 60_000).toISOString();

    // Housekeeping first — the table is a rolling window, not a log.
    await admin.from("password_reset_attempts").delete().lt("requested_at", new Date(now - 24 * 3600_000).toISOString());

    const [byEmail, byIp] = await Promise.all([
      admin.from("password_reset_attempts").select("id", { count: "exact", head: true }).eq("email_key", emailKey).gte("requested_at", since(PER_EMAIL.minutes)),
      ip
        ? admin.from("password_reset_attempts").select("id", { count: "exact", head: true }).eq("ip", ip).gte("requested_at", since(PER_IP.minutes))
        : Promise.resolve({ count: 0 }),
    ]);

    if ((byEmail.count ?? 0) >= PER_EMAIL.max) return { error: "Too many attempts for that address. Wait a few minutes and try again." };
    if (((byIp as { count: number | null }).count ?? 0) >= PER_IP.max) return { error: "Too many attempts from this connection. Wait a few minutes and try again." };

    // Recorded BEFORE the lookup, so a probe costs quota whether the address
    // exists or not. This is the brake on walking the staff list.
    await admin.from("password_reset_attempts").insert({ email_key: emailKey, ip });

    const staff = await findStaff(admin, emailKey);
    if (!staff) return { error: "There's no account with that email. Check the spelling, or ask the owner to add you." };
    if (!staff.isActive) return { error: "That account has been switched off. Ask the owner to switch it back on." };

    // generateLink MINTS the token without sending anything — the same call
    // /api/pos/pin-login already relies on. We deliver it ourselves.
    const { data: link, error: linkErr } = await admin.auth.admin.generateLink({ type: "recovery", email: staff.email });
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const tokenHash = (link as any)?.properties?.hashed_token as string | undefined;
    if (linkErr || !tokenHash) return { error: "Something went wrong preparing your link. Try again in a moment." };

    const sent = await sendPasswordResetEmail({
      to: staff.email,
      name: staff.name,
      link: `${origin}/auth/reset?token_hash=${encodeURIComponent(tokenHash)}`,
      minutes: LINK_MINUTES,
    });
    // Say so. Claiming success while the mailer is down is how someone ends up
    // refreshing an inbox for an hour.
    if (!sent.ok) return { error: "We couldn't send the email just now. Try again in a minute." };

    return { sent: true, sentTo: staff.email };
  } catch {
    return { error: "Something went wrong. Try again in a moment." };
  }
}

/** The account behind an address, active or not — the caller decides what to say. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function findStaff(admin: any, emailKey: string): Promise<{ email: string; name: string; isActive: boolean } | null> {
  // auth.users isn't reachable through PostgREST, so the address→user lookup has
  // to go through the admin API. listUsers is paginated; the studio has eight
  // staff, but page through anyway rather than quietly miss the ninth and tell
  // a real person they don't exist.
  for (let page = 1; page <= 5; page++) {
    const { data, error } = await admin.auth.admin.listUsers({ page, perPage: 200 });
    if (error) return null;
    const users = data?.users ?? [];
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const hit = users.find((u: any) => (u.email ?? "").toLowerCase() === emailKey);
    if (hit) {
      const { data: row } = await admin.from("app_users").select("display_name, is_active").eq("auth_user_id", hit.id).maybeSingle();
      const staff = row as { display_name: string | null; is_active: boolean } | null;
      // An auth user with no staff row is an orphan (the +anesh one, say) — it
      // can't sign in anywhere, so it isn't an account as far as this page cares.
      if (!staff) return null;
      return { email: hit.email as string, name: staff.display_name || "there", isActive: staff.is_active };
    }
    if (users.length < 200) break;
  }
  return null;
}

/** The origin this request arrived on — the reset link has to point back here,
 *  not at a hardcoded domain that would break on a preview deployment. */
function originFrom(h: Headers): string {
  const host = h.get("x-forwarded-host") ?? h.get("host") ?? "app-carfectionist.com";
  const proto = h.get("x-forwarded-proto") ?? (host.startsWith("localhost") || host.startsWith("127.0.0.1") ? "http" : "https");
  return `${proto}://${host}`;
}
