"use server";

import { headers } from "next/headers";
import { createAdminClient } from "@/lib/supabase/admin";
import { sendPasswordResetEmail } from "@/lib/email";

// "I forgot my password."
//
// This is the only place in the app that emails an address a stranger typed, so
// it is the only place we can be used to spam someone else — or to grind through
// addresses learning which ones have accounts. Two rules follow from that:
//
//  1. The answer NEVER changes. Unknown address, deactivated staff, email
//     provider down — the page says the same thing every time. Anything else is
//     a free account-enumeration oracle, and "no account with that email" is the
//     classic way to leak your entire staff list.
//  2. It is throttled, per address and per IP, because rule 1 makes the abuse
//     silent.
//
// The link itself is a Supabase recovery token generated by the service role and
// delivered by OUR mailer — see sendPasswordResetEmail for why not Supabase's.

export interface ForgotState {
  sent?: boolean;
  error?: string;
}

/** Same words whatever happened. Deliberate — see rule 1. */
const SENT: ForgotState = { sent: true };

const PER_EMAIL = { max: 3, minutes: 15 };
const PER_IP = { max: 10, minutes: 60 };
const LINK_MINUTES = 60; // Supabase's default recovery TTL

export async function requestPasswordReset(_prev: ForgotState, formData: FormData): Promise<ForgotState> {
  const raw = String(formData.get("email") ?? "").trim();
  const emailKey = raw.toLowerCase();
  if (!raw || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(raw)) return { error: "Enter a valid email address." };

  const h = await headers();
  const ip = h.get("cf-connecting-ip") ?? h.get("x-forwarded-for")?.split(",")[0]?.trim() ?? null;
  const origin = originFrom(h);

  // The service role is the only thing that touches the throttle table (RLS is
  // on with no policies) and the only thing that can mint a recovery token.
  const admin = createAdminClient();

  try {
    const now = Date.now();
    const since = (mins: number) => new Date(now - mins * 60_000).toISOString();

    // Housekeeping first — the table is a rolling window, not a log.
    await admin.from("password_reset_attempts").delete().lt("requested_at", new Date(now - 24 * 3600_000).toISOString());

    const [byEmail, byIp] = await Promise.all([
      admin.from("password_reset_attempts").select("id", { count: "exact", head: true }).eq("email_key", emailKey).gte("requested_at", since(PER_EMAIL.minutes)),
      ip
        ? admin.from("password_reset_attempts").select("id", { count: "exact", head: true }).eq("ip", ip).gte("requested_at", since(PER_IP.minutes))
        : Promise.resolve({ count: 0 }),
    ]);

    if ((byEmail.count ?? 0) >= PER_EMAIL.max || ((byIp as { count: number | null }).count ?? 0) >= PER_IP.max) {
      // Still the same answer. A throttle message would itself be a signal.
      return SENT;
    }
    await admin.from("password_reset_attempts").insert({ email_key: emailKey, ip });

    // Who is this? An address with no account, or a deactivated staff member,
    // gets nothing — but says nothing either.
    const target = await findActiveStaff(admin, emailKey);
    if (!target) return SENT;

    // generateLink MINTS the token without sending anything — the same call
    // /api/pos/pin-login already relies on. We deliver it ourselves.
    const { data: link, error: linkErr } = await admin.auth.admin.generateLink({ type: "recovery", email: target.email });
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const tokenHash = (link as any)?.properties?.hashed_token as string | undefined;
    if (linkErr || !tokenHash) return SENT;

    await sendPasswordResetEmail({
      to: target.email,
      name: target.name,
      link: `${origin}/auth/reset?token_hash=${encodeURIComponent(tokenHash)}`,
      minutes: LINK_MINUTES,
    });
  } catch {
    /* swallow — see rule 1 */
  }
  return SENT;
}

/** The email's real owner, only if their account is still active. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function findActiveStaff(admin: any, emailKey: string): Promise<{ email: string; name: string } | null> {
  // auth.users isn't reachable through PostgREST, so the address→user lookup has
  // to go through the admin API. listUsers is paginated; the studio has eight
  // staff, but page through anyway rather than quietly miss the ninth.
  for (let page = 1; page <= 5; page++) {
    const { data, error } = await admin.auth.admin.listUsers({ page, perPage: 200 });
    if (error) return null;
    const users = data?.users ?? [];
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const hit = users.find((u: any) => (u.email ?? "").toLowerCase() === emailKey);
    if (hit) {
      const { data: row } = await admin.from("app_users").select("display_name, is_active").eq("auth_user_id", hit.id).maybeSingle();
      const staff = row as { display_name: string | null; is_active: boolean } | null;
      // No row, or switched off → no reset. Someone who has been deactivated
      // must not be able to let themselves back in.
      if (!staff?.is_active) return null;
      return { email: hit.email as string, name: staff.display_name || "there" };
    }
    if (users.length < 200) break;
  }
  return null;
}

/** The origin this request arrived on — the reset link has to point back here,
 *  not at a hardcoded domain that would break on a preview deployment. */
function originFrom(h: Headers): string {
  const host = h.get("x-forwarded-host") ?? h.get("host") ?? "app-carfectionist.com";
  const proto = h.get("x-forwarded-proto") ?? (host.startsWith("localhost") || host.startsWith("127.0.0.1") ? "http" : "https");
  return `${proto}://${host}`;
}
