import type { SupabaseClient } from "@supabase/supabase-js";
import { getDocumentProps } from "@/lib/supabase/queries/render";
import { renderDocumentPdf } from "@/lib/pdf/document-pdf";
import { PdfConfigError } from "@/lib/pdf/render";
import { sendDocumentEmail } from "@/lib/email";
import { docToken } from "@/lib/receipt-token";
import { normalizePhoneMU } from "@/lib/phone";
import { createAdminClient } from "@/lib/supabase/admin";
import { recordOutbound } from "@/lib/wa-inbox";
import * as wa from "@/lib/whatsapp";

// One send path for tablet + web: render the exact document PDF and deliver it
// by email (attachment + download link) or WhatsApp (utility template with a
// DOCUMENT header — Meta fetches the tokenized public PDF URL).
//
// The WhatsApp route needs a Meta-approved utility template. We bootstrap it
// on first use: insert the wa_templates row + submit to Meta, and tell the
// operator to retry once it's approved (usually minutes).

// The message mirrors the owner's Refrens reference (PDF attached + structured
// confirmation + View button), with two deliberate departures:
//  - Refrens says "replies to this number are not monitored" — ours ARE (the
//    inbox is the whole point of the dedicated number), so we invite replies.
//  - {{6}} carries the operator's note (preset or edited freely) — Meta only
//    delivers pre-approved templates, so free text rides inside the template.
//
// Creation rules Meta enforces: a media header needs an example handle, a URL
// button's variable must be a trailing suffix (hence /d/<token>), variables
// can't open or close the body, and there must be enough fixed words per
// variable ("params words ratio") — the long fixed text keeps that ratio safe.
// One template per document kind so the fixed wording reads naturally
// ("Quotation No:", "Invoice No:").
const KIND_CAP: Record<string, string> = { quote: "Quotation", invoice: "Invoice", credit_note: "Credit Note" };

function docTemplate(docType: string) {
  const K = KIND_CAP[docType] ?? "Document";
  return {
    name: `document_${docType}`, // document_quote | document_invoice | document_credit_note
    language: "en",
    category: "UTILITY",
    body: `Hello {{1}},

This is to confirm that the ${K} for {{2}} is generated by Carfectionist.

${K} No: {{3}}
Amount: {{4}}
${K} Date: {{5}}

The ${K} is attached here and can be viewed from the link below.

{{6}}

If you need assistance, simply reply to this message or call us on +230 5258 8854.

Thank you!`,
    variableExamples: ["INTERGRAH LTEE", "INTERGRAH LTEE", "A00120", "MUR 2,547.25", "Jul 11, 2026", "Thank you for your business."],
    headerFormat: "DOCUMENT" as const,
    urlButton: { text: "View", urlBase: "https://app-carfectionist.com/d/", exampleSuffix: "QWJjMTIz.c2FtcGxldG9rZW4" },
  };
}

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

/** "2026-07-11" → "Jul 11, 2026" (fixed en format, no Intl variance). */
function prettyDate(iso: string | null): string {
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(iso ?? "");
  if (!m) return "—";
  return `${MONTHS[Number(m[2]) - 1]} ${Number(m[3])}, ${m[1]}`;
}

/** 2547.25 → "MUR 2,547.25" — matches the reference message's amount format. */
function prettyMUR(n: number): string {
  const [int, dec] = n.toFixed(2).split(".");
  return `MUR ${int.replace(/\B(?=(\d{3})+(?!\d))/g, ",")}.${dec}`;
}

/** "INTERGRAH LTEE" → "intergrah-ltee" for the attachment filename. */
function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40) || "customer";
}

export const DEFAULT_SEND_NOTE = "Thank you for your business.";

// A minimal valid 1-page PDF, used ONLY as the template's header example at
// creation time (Meta requires a sample document for a DOCUMENT header). The
// real quote/invoice PDF is fetched from its link at send time.
const SAMPLE_PDF = new Uint8Array(
  Buffer.from(
    "JVBERi0xLjQKMSAwIG9iago8PC9UeXBlL0NhdGFsb2cvUGFnZXMgMiAwIFI+PgplbmRvYmoKMiAwIG9iago8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PgplbmRvYmoKMyAwIG9iago8PC9UeXBlL1BhZ2UvUGFyZW50IDIgMCBSL01lZGlhQm94WzAgMCA1OTUgODQyXS9SZXNvdXJjZXM8PC9Gb250PDwvRjEgNCAwIFI+Pj4+L0NvbnRlbnRzIDUgMCBSPj4KZW5kb2JqCjQgMCBvYmoKPDwvVHlwZS9Gb250L1N1YnR5cGUvVHlwZTEvQmFzZUZvbnQvSGVsdmV0aWNhPj4KZW5kb2JqCjUgMCBvYmoKPDwvTGVuZ3RoIDQ0Pj4Kc3RyZWFtCkJUIC9GMSAxOCBUZiA2MCA3ODAgVGQgKENhcmZlY3Rpb25pc3QpIFRqIEVUCmVuZHN0cmVhbQplbmRvYmoKeHJlZgowIDYKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDAwMDA5IDAwMDAwIG4gCjAwMDAwMDAwNTQgMDAwMDAgbiAKMDAwMDAwMDEwNSAwMDAwMCBuIAowMDAwMDAwMjE3IDAwMDAwIG4gCjAwMDAwMDAyODAgMDAwMDAgbiAKdHJhaWxlcgo8PC9TaXplIDYvUm9vdCAxIDAgUj4+CnN0YXJ0eHJlZgozNzIKJSVFT0Y=",
    "base64",
  ),
);

export interface SendDocumentInput {
  sb: SupabaseClient; // RLS-scoped client of the operator (cookie or bearer)
  docId: string;
  channel: "email" | "whatsapp";
  to: string;
  note?: string | null; // operator's message to the customer (preset or edited)
  saveContact?: boolean;
  origin: string; // https://app-carfectionist.com — for the public PDF link
  deviceCode?: string | null; // stamps the traceability event when sent from a tablet
}

export type SendDocumentResult = { ok: true } | { ok: false; error: string };

const KIND_LABEL: Record<string, string> = { quote: "quotation", invoice: "invoice", credit_note: "credit note" };

export async function sendDocument(i: SendDocumentInput): Promise<SendDocumentResult> {
  /* eslint-disable @typescript-eslint/no-explicit-any */
  const sb = i.sb as SupabaseClient<any>;

  // Load the document through the operator's RLS — also proves they may see it.
  const { data: doc } = await sb
    .from("documents")
    .select("id, tenant_id, doc_type, number, status, total_incl, issue_date, customer_id, accepted_signature, customers(name)")
    .eq("id", i.docId)
    .maybeSingle();
  if (!doc) return { ok: false, error: "Document not found." };
  const d: any = doc;
  if (!d.number) return { ok: false, error: "This document is still a draft — issue or accept it first." };
  const kind = KIND_LABEL[d.doc_type] ?? "document";
  const customerName: string = d.customers?.name ?? "customer";

  const to = i.to.trim();
  if (!to) return { ok: false, error: "Enter where to send it." };
  // One line, bounded — WhatsApp template variables reject newlines/tabs.
  const note = (i.note ?? "").replace(/\s+/g, " ").trim().slice(0, 300) || DEFAULT_SEND_NOTE;

  if (i.channel === "email") {
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(to)) return { ok: false, error: "That email address doesn't look right." };

    const props = await getDocumentProps(i.docId, sb);
    if (!props) return { ok: false, error: "Document not found." };
    let pdf: ArrayBuffer;
    try {
      pdf = await renderDocumentPdf(props, i.origin);
    } catch (e) {
      if (e instanceof PdfConfigError) return { ok: false, error: "PDF generation isn't configured on this deployment." };
      return { ok: false, error: `Could not render the PDF: ${(e as Error).message}` };
    }
    const link = `${i.origin}/api/public/doc/${encodeURIComponent(await docToken(i.docId))}/pdf`;
    const r = await sendDocumentEmail({
      to,
      docKind: kind,
      number: d.number,
      customerName,
      totalCents: Math.round(Number(d.total_incl) * 100),
      accepted: !!d.accepted_signature,
      note,
      pdfBase64: Buffer.from(pdf).toString("base64"),
      downloadLink: link,
      studioName: "Carfectionist",
    });
    if (!r.ok) return r;
  } else {
    const phone = normalizePhoneMU(to);
    if (!phone) return { ok: false, error: "That phone number doesn't look right." };
    if (!wa.isConfigured()) return { ok: false, error: "WhatsApp isn't connected yet — finish the Meta setup first." };

    const TPL = docTemplate(d.doc_type);

    // The utility template is server-managed bookkeeping (owner-only RLS would
    // block non-owner operators) → admin client for wa_templates only.
    const admin = createAdminClient();
    const { data: tpl } = await admin
      .from("wa_templates")
      .select("id, status")
      .eq("name", TPL.name)
      .eq("language", TPL.language)
      .maybeSingle();

    if (!tpl) {
      // A DOCUMENT-header template must be created WITH an example document
      // (Meta #100/2388043). Upload a tiny sample once to get a header handle.
      const sample = await wa.uploadHeaderSample(SAMPLE_PDF, "sample.pdf", "application/pdf");
      if (!sample.ok) return { ok: false, error: `Couldn't set up the WhatsApp document template: ${sample.error}` };
      const sub = await wa.submitTemplate({ ...TPL, headerHandle: sample.data });
      if (!sub.ok) return sub;
      await admin.from("wa_templates").insert({
        tenant_id: d.tenant_id,
        name: TPL.name,
        language: TPL.language,
        category: TPL.category,
        body: TPL.body,
        variable_count: 6,
        status: "pending",
        meta_template_id: sub.data.id,
      });
      return { ok: false, error: "One-time setup: the document template was just submitted to WhatsApp for approval. Try again in a few minutes." };
    }
    if (tpl.status !== "approved") {
      return { ok: false, error: "The WhatsApp document template is still pending approval — try again shortly (or press Sync approvals in Marketing)." };
    }

    const token = await docToken(i.docId);
    const link = `${i.origin}/api/public/doc/${encodeURIComponent(token)}/pdf`;
    const K = KIND_CAP[d.doc_type] ?? "Document";
    const r = await wa.sendDocumentTemplate(
      phone,
      TPL.name,
      TPL.language,
      // {{1}} name · {{2}} name · {{3}} number · {{4}} amount · {{5}} date · {{6}} note
      [customerName, customerName, d.number, prettyMUR(Number(d.total_incl)), prettyDate(d.issue_date), note],
      // filename mirrors the reference: quotation-a00120-carfectionist-intergrah-ltee.pdf
      { link, filename: `${K.toLowerCase().replace(/\s+/g, "-")}-${String(d.number).toLowerCase()}-carfectionist-${slug(customerName)}.pdf` },
      encodeURIComponent(token), // the View button's /d/<token> suffix
    );
    if (!r.ok) return r;

    // Thread it into the customer's conversation so the inbox reads as one
    // story: "we sent A00004" → their reply lands right under it.
    await recordOutbound(createAdminClient(), {
      tenantId: d.tenant_id,
      phone,
      body: `${kind.charAt(0).toUpperCase() + kind.slice(1)} ${d.number} sent. ${note}`,
      waMessageId: r.data.messageId,
      msgType: "document",
      refType: "document",
      refId: d.id,
      customerId: d.customer_id ?? null,
    });
  }

  // Optionally save a newly-captured address/number back onto the customer.
  if (i.saveContact && d.customer_id) {
    const patch = i.channel === "email" ? { email: to } : { phone: to };
    await sb.from("customers").update(patch).eq("id", d.customer_id);
  }

  // Traceability: who sent what where (device-stamped when from a tablet).
  const { data: me } = await sb.auth.getUser();
  const { data: appUser } = me?.user
    ? await sb.from("app_users").select("id").eq("auth_user_id", me.user.id).maybeSingle()
    : { data: null };
  await sb.from("audit_events").insert({
    tenant_id: d.tenant_id,
    actor_id: (appUser as any)?.id ?? null,
    event_type: "document_sent",
    ref_type: "document",
    ref_id: d.id,
    payload: { channel: i.channel, to, number: d.number, kind },
    device_id: i.deviceCode ?? null,
  });
  /* eslint-enable @typescript-eslint/no-explicit-any */

  return { ok: true };
}
